<?php
namespace Tiny\Http;

class HttpConstants {
    /*
     * RESPONSE
     */
    ## CONTENT ENCODING
    const CONTENT_ENCODING_COMPRESS = "compress";
    const CONTENT_ENCODING_DEFLATE = "deflate";
    const CONTENT_ENCODING_EXI = "exi";
    const CONTENT_ENCODING_GZIP = "gzip";
    const CONTENT_ENCODING_IDENTITY = "identity";
    const CONTENT_ENCODING_PACK200_GZIP = "pack200-gzip";
    const CONTENT_ENCODING_X_COMPRESS = "x-compress";
    const CONTENT_ENCODING_X_GZIP = "x-gzip";
    ## TRANSFERT ENCODING
    const TRANSFERT_ENCODING_CHUNKED = "chunked";
    const TRANSFERT_ENCODING_COMPRESS = "compress";
    const TRANSFERT_ENCODING_DEFLATE = "deflate";
    const TRANSFERT_ENCODING_GZIP = "gzip";
    const TRANSFERT_ENCODING_IDENTITY = "identity";
    const TRANSFERT_ENCODING_X_COMPRESS = "x-compress";
    const TRANSFERT_ENCODING_X_GZIP = "x-gzip";
    ## STATUS_CODE
    //100
    const _100_CONTINUE = 100;
    const _101_SWITCHING_PROTOCOLS = 101;
    const _102_PROCESSING = 102;
    //200
    const _200_OK = 200;
    const _201_CREATED = 201;
    const _202_ACCEPTED = 202;
    const _203_NON_AUTHORITATIVE_INFORMATION = 203;
    const _204_NO_CONTENT = 204;
    const _205_RESET_CONTENT = 205;
    const _206_PARTIAL_CONTENT = 206;
    const _207_MULTI_STATUS = 207;
    const _210_CONTENT_DIFFERENT = 210;
    const _226_IM_USED = 226;
    //300
    const _300_MULTIPLE_CHOICES = 300;
    const _301_MOVED_PERMANENTLY = 301;
    const _302_MOVED_TEMPORARILY = 302;
    const _303_SEE_OTHER = 303;
    const _304_NOT_MODIFIED = 304;
    const _305_USE_PROXY = 305;
    const _307_TEMPORARY_REDIRECT = 307;
    const _308_PERMANENT_REDIRECT = 308;
    const _310_TOO_MANY_REDIRECTS = 310;
    //400
    const _400_BAD_REQUEST = 400;
    const _401_UNAUTHORIZED = 401;
    const _402_PAYMENT_REQUIRED = 402;
    const _403_FORBIDDEN = 403;
    const _404_NOT_FOUND = 404;
    const _405_METHOD_NOT_ALLOWED = 405;
    const _406_NOT_ACCEPTABLE = 406;
    const _407_PROXY_AUTHENTICATION_REQUIRED = 407;
    const _408_REQUEST_TIME_OUT = 408;
    const _409_CONFLICT = 409;
    const _410_GONE = 410;
    const _411_LENGTH_REQUIRED = 411;
    const _412_PRECONDITION_FAILED = 412;
    const _413_REQUEST_ENTITY_TOO_LARGE = 413;
    const _414_REQUEST_URI_Too_Long = 414;
    const _415_UNSUPPORTED_MEDIA_TYPE = 415;
    const _416_REQUESTED_RANGE_UNSATISFIABLE = 416;
    const _417_EXPECTATION_FAILED = 417;
    const _418_IM_A_TEAPOT = 418;
    const _422_UNPROCESSABLE_ENTITY = 422;
    const _423_LOCKED = 423;
    const _424_METHOD_FAILURE = 424;
    const _425_UNORDERED_COLLECTION = 425;
    const _426_UPGRADE_REQUIRED = 426;
    const _428_PRECONDITION_REQUIRED = 428;
    const _429_TOO_MANY_REQUESTS = 429;
    const _431_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    const _449_RETRY_WITH = 449;
    const _450_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS = 450;
    const _451_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    const _456_UNRECOVERABLE_ERROR = 456;
    const _499_CLIENT_HAS_CLOSED_CONNECTION = 499;
    //500
    const _500_INTERNAL_SERVER_ERROR = 500;
    const _501_NOT_IMPLEMENTED = 501;
    const _502_BAD_GATEWAY = 502;
    const _503_SERVICE_UNAVAILABLE = 503;
    const _504_GATEWAY_TIME_OUT = 504;
    const _505_HTTP_VERSION_NOT_SUPPORTED = 505;
    const _506_VARIANT_ALSO_NEGOCIATE = 506;
    const _507_INSUFFICIENT_STORAGE = 507;
    const _508_LOOP_DETECTED = 508;
    const _509_BANDWIDTH_LIMIT_EXCEEDED = 509;
    const _510_NOT_EXTENDED = 510;
    const _511_NETWORK_AUTHENTICATION_REQUIRED = 511;
    const _520_WEB_SERVER_IS_RETURNING_AN_UNKNOWN_ERROR = 520;
    ## CONTENT_TYPE
    const CONTENT_TYPE_JSON = "application/json";
    const CONTENT_TYPE_HTML = "text/html";
    const CONTENT_TYPE_7ZIP = "application/x-7z-compressed";
    const CONTENT_TYPE_LOL = "application/x-shockwave-flash";
    const CONTENT_TYPE_PDF = "application/pdf";
    const CONTENT_TYPE_XDP = "application/vnd.adobe.xdp+xml";
    const CONTENT_TYPE_XFDF = "application/vnd.adobe.xfdf";
    const CONTENT_TYPE_BINARY_DATA = "application/octet-stream";
    const CONTENT_TYPE_BMP = "image/bmp";
    const CONTENT_TYPE_CSS = "text/css";
    const CONTENT_TYPE_CSV = "text/csv";
    const CONTENT_TYPE_XML_DTD = "application/xml-dtd";
    const CONTENT_TYPE_ICAL = "text/calendar";
    const CONTENT_TYPE_XICON = "image/x-icon";
    const CONTENT_TYPE_JAVA_ARCHIVE = "application/java-archive";
    const CONTENT_TYPE_JAVASCRIPT = "application/javascript";
    const CONTENT_TYPE_JPEG = "image/jpeg";
    const CONTENT_TYPE_EXCEL = "application/vnd.ms-excel";
    const CONTENT_TYPE_EXCEL_WORKBOOK = "application/vnd.ms-excel.sheet.binary.macroenabled.12";
    const CONTENT_TYPE_AUDIO_MPEG = "audio/mpeg";
    const CONTENT_TYPE_VIDEO_MPEG = "video/mpeg";
    const CONTENT_TYPE_AUDIO_MP4 = "audio/mp4";
    const CONTENT_TYPE_VIDEO_MP4 = "video/mp4";
    const CONTENT_TYPE_AUDIO_OGG = "audio/ogg";
    const CONTENT_TYPE_VIDEO_OGG = "video/ogg";
    const CONTENT_TYPE_OPENDOCUMENT_SPREADSHEET = "application/vnd.oasis.opendocument.spreadsheet";
    const CONTENT_TYPE_OPENDOCUMENT_SPREADSHEET_TEMPLATE = "application/vnd.oasis.opendocument.spreadsheet-template";
    const CONTENT_TYPE_OPENDOCUMENT_TEXT = "application/vnd.oasis.opendocument.text";
    const CONTENT_TYPE_OPENDOCUMENT_TEXT_MASTER = "application/vnd.oasis.opendocument.text-master";
    const CONTENT_TYPE_OPENDOCUMENT_TEXT_TEMPLATE = "application/vnd.oasis.opendocument.text-template";
    const CONTENT_TYPE_OPENOFFICE_CALC = "application/vnd.sun.xml.calc";
    const CONTENT_TYPE_OPENOFFICE_CALC_TEMPLATE = "application/vnd.sun.xml.calc.template";
    const CONTENT_TYPE_PNG = "image/png";
    const CONTENT_TYPE_RAR = "application/x-rar-compressed";
    const CONTENT_TYPE_APP_RTF = "application/rtf";
    const CONTENT_TYPE_RTF = "text/richtext";
    const CONTENT_TYPE_SVG = "image/svg+xml";
    const CONTENT_TYPE_TAR = "application/x-tar";
    const CONTENT_TYPE_TEXT_PLAIN = "text/plain";
    const CONTENT_TYPE_VCALENDAR = "text/x-vcalendar";
    const CONTENT_TYPE_VCARD = "text/x-vcard";
    const CONTENT_TYPE_XHTML = "application/xhtml+xml";
    const CONTENT_TYPE_XML = "application/xml";
    const CONTENT_TYPE_ZIP = "application/zip";
    ## CONTENT_LANGUAGE
    const CONTENT_LANGUAGE_AFGHANISTAN = "af";
    const CONTENT_LANGUAGE_ALAND_ISLANDS = "ax";
    const CONTENT_LANGUAGE_ALBANIA = "al";
    const CONTENT_LANGUAGE_ALGERIA = "dz";
    const CONTENT_LANGUAGE_AMERICAN_SAMOA = "as";
    const CONTENT_LANGUAGE_ANDORRA = "ad";
    const CONTENT_LANGUAGE_ANGOLA = "ao";
    const CONTENT_LANGUAGE_ANGUILLA = "ai";
    const CONTENT_LANGUAGE_ANTARCTICA = "aq";
    const CONTENT_LANGUAGE_ANTIGUA_AND_BARBUDA = "ag";
    const CONTENT_LANGUAGE_ARGENTINA = "ar";
    const CONTENT_LANGUAGE_ARMENIA = "am";
    const CONTENT_LANGUAGE_ARUBA = "aw";
    const CONTENT_LANGUAGE_AUSTRALIA = "au";
    const CONTENT_LANGUAGE_AUSTRIA = "at";
    const CONTENT_LANGUAGE_AZERBAIJAN = "az";
    const CONTENT_LANGUAGE_BAHAMAS = "bs";
    const CONTENT_LANGUAGE_BAHRAIN = "bh";
    const CONTENT_LANGUAGE_BANGLADESH = "bd";
    const CONTENT_LANGUAGE_BARBADOS = "bb";
    const CONTENT_LANGUAGE_BELARUS = "by";
    const CONTENT_LANGUAGE_BELGIUM = "be";
    const CONTENT_LANGUAGE_BELIZE = "bz";
    const CONTENT_LANGUAGE_BENIN = "bj";
    const CONTENT_LANGUAGE_BERMUDA = "bm";
    const CONTENT_LANGUAGE_BHUTAN = "bt";
    const CONTENT_LANGUAGE_BOLIVIA_PLURINATIONAL_STATE_OF = "bo";
    const CONTENT_LANGUAGE_BONAIRE_SINT_EUSTATIUS_AND_SABA = "bq";
    const CONTENT_LANGUAGE_BOSNIA_AND_HERZEGOVINA = "ba";
    const CONTENT_LANGUAGE_BOTSWANA = "bw";
    const CONTENT_LANGUAGE_BOUVET_ISLAND = "bv";
    const CONTENT_LANGUAGE_BRAZIL = "br";
    const CONTENT_LANGUAGE_BRITISH_INDIAN_OCEAN_TERRITORY = "io";
    const CONTENT_LANGUAGE_BRUNEI_DARUSSALAM = "bn";
    const CONTENT_LANGUAGE_BULGARIA = "bg";
    const CONTENT_LANGUAGE_BURKINA_FASO = "bf";
    const CONTENT_LANGUAGE_BURUNDI = "bi";
    const CONTENT_LANGUAGE_CAMBODIA = "kh";
    const CONTENT_LANGUAGE_CAMEROON = "cm";
    const CONTENT_LANGUAGE_CANADA = "ca";
    const CONTENT_LANGUAGE_CAPE_VERDE = "cv";
    const CONTENT_LANGUAGE_CAYMAN_ISLANDS = "ky";
    const CONTENT_LANGUAGE_CENTRAL_AFRICAN_REPUBLIC = "cf";
    const CONTENT_LANGUAGE_CHAD = "td";
    const CONTENT_LANGUAGE_CHILE = "cl";
    const CONTENT_LANGUAGE_CHINA = "cn";
    const CONTENT_LANGUAGE_CHRISTMAS_ISLAND = "cx";
    const CONTENT_LANGUAGE_COCOS_KEELING_ISLANDS = "cc";
    const CONTENT_LANGUAGE_COLOMBIA = "co";
    const CONTENT_LANGUAGE_COMOROS = "km";
    const CONTENT_LANGUAGE_CONGO = "cg";
    const CONTENT_LANGUAGE_CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE = "cd";
    const CONTENT_LANGUAGE_COOK_ISLANDS = "ck";
    const CONTENT_LANGUAGE_COSTA_RICA = "cr";
    const CONTENT_LANGUAGE_CÔTE_DIVOIRE = "ci";
    const CONTENT_LANGUAGE_CROATIA = "hr";
    const CONTENT_LANGUAGE_CUBA = "cu";
    const CONTENT_LANGUAGE_CURAÇAO = "cw";
    const CONTENT_LANGUAGE_CYPRUS = "cy";
    const CONTENT_LANGUAGE_CZECH_REPUBLIC = "cz";
    const CONTENT_LANGUAGE_DENMARK = "dk";
    const CONTENT_LANGUAGE_DJIBOUTI = "dj";
    const CONTENT_LANGUAGE_DOMINICA = "dm";
    const CONTENT_LANGUAGE_DOMINICAN_REPUBLIC = "do";
    const CONTENT_LANGUAGE_ECUADOR = "ec";
    const CONTENT_LANGUAGE_EGYPT = "eg";
    const CONTENT_LANGUAGE_EL_SALVADOR = "sv";
    const CONTENT_LANGUAGE_EQUATORIAL_GUINEA = "gq";
    const CONTENT_LANGUAGE_ERITREA = "er";
    const CONTENT_LANGUAGE_ESTONIA = "ee";
    const CONTENT_LANGUAGE_ETHIOPIA = "et";
    const CONTENT_LANGUAGE_FALKLAND_ISLANDS_MALVINAS = "fk";
    const CONTENT_LANGUAGE_FAROE_ISLANDS = "fo";
    const CONTENT_LANGUAGE_FIJI = "fj";
    const CONTENT_LANGUAGE_FINLAND = "fi";
    const CONTENT_LANGUAGE_FRANCE = "fr";
    const CONTENT_LANGUAGE_FRENCH_GUIANA = "gf";
    const CONTENT_LANGUAGE_FRENCH_POLYNESIA = "pf";
    const CONTENT_LANGUAGE_FRENCH_SOUTHERN_TERRITORIES = "tf";
    const CONTENT_LANGUAGE_GABON = "ga";
    const CONTENT_LANGUAGE_GAMBIA = "gm";
    const CONTENT_LANGUAGE_GEORGIA = "ge";
    const CONTENT_LANGUAGE_GERMANY = "de";
    const CONTENT_LANGUAGE_GHANA = "gh";
    const CONTENT_LANGUAGE_GIBRALTAR = "gi";
    const CONTENT_LANGUAGE_GREECE = "gr";
    const CONTENT_LANGUAGE_GREENLAND = "gl";
    const CONTENT_LANGUAGE_GRENADA = "gd";
    const CONTENT_LANGUAGE_GUADELOUPE = "gp";
    const CONTENT_LANGUAGE_GUAM = "gu";
    const CONTENT_LANGUAGE_GUATEMALA = "gt";
    const CONTENT_LANGUAGE_GUERNSEY = "gg";
    const CONTENT_LANGUAGE_GUINEA = "gn";
    const CONTENT_LANGUAGE_GUINEA_BISSAU = "gw";
    const CONTENT_LANGUAGE_GUYANA = "gy";
    const CONTENT_LANGUAGE_HAITI = "ht";
    const CONTENT_LANGUAGE_HEARD_ISLAND_AND_MCDONALD_ISLANDS = "hm";
    const CONTENT_LANGUAGE_HOLY_SEE_VATICAN_CITY_STATE = "va";
    const CONTENT_LANGUAGE_HONDURAS = "hn";
    const CONTENT_LANGUAGE_HONG_KONG = "hk";
    const CONTENT_LANGUAGE_HUNGARY = "hu";
    const CONTENT_LANGUAGE_ICELAND = "is";
    const CONTENT_LANGUAGE_INDIA = "in";
    const CONTENT_LANGUAGE_INDONESIA = "id";
    const CONTENT_LANGUAGE_IRAN_ISLAMIC_REPUBLIC_OF = "ir";
    const CONTENT_LANGUAGE_IRAQ = "iq";
    const CONTENT_LANGUAGE_IRELAND = "ie";
    const CONTENT_LANGUAGE_ISLE_OF_MAN = "im";
    const CONTENT_LANGUAGE_ISRAEL = "il";
    const CONTENT_LANGUAGE_ITALY = "it";
    const CONTENT_LANGUAGE_JAMAICA = "jm";
    const CONTENT_LANGUAGE_JAPAN = "jp";
    const CONTENT_LANGUAGE_JERSEY = "je";
    const CONTENT_LANGUAGE_JORDAN = "jo";
    const CONTENT_LANGUAGE_KAZAKHSTAN = "kz";
    const CONTENT_LANGUAGE_KENYA = "ke";
    const CONTENT_LANGUAGE_KIRIBATI = "ki";
    const CONTENT_LANGUAGE_KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF = "kp";
    const CONTENT_LANGUAGE_KOREA_REPUBLIC_OF = "kr";
    const CONTENT_LANGUAGE_KUWAIT = "kw";
    const CONTENT_LANGUAGE_KYRGYZSTAN = "kg";
    const CONTENT_LANGUAGE_LAO_PEOPLES_DEMOCRATIC_REPUBLIC = "la";
    const CONTENT_LANGUAGE_LATVIA = "lv";
    const CONTENT_LANGUAGE_LEBANON = "lb";
    const CONTENT_LANGUAGE_LESOTHO = "ls";
    const CONTENT_LANGUAGE_LIBERIA = "lr";
    const CONTENT_LANGUAGE_LIBYA = "ly";
    const CONTENT_LANGUAGE_LIECHTENSTEIN = "li";
    const CONTENT_LANGUAGE_LITHUANIA = "lt";
    const CONTENT_LANGUAGE_LUXEMBOURG = "lu";
    const CONTENT_LANGUAGE_MACAO = "mo";
    const CONTENT_LANGUAGE_MACEDONIA_THE_FORMER_YUGOSLAV_REPUBLIC_OF = "mk";
    const CONTENT_LANGUAGE_MADAGASCAR = "mg";
    const CONTENT_LANGUAGE_MALAWI = "mw";
    const CONTENT_LANGUAGE_MALAYSIA = "my";
    const CONTENT_LANGUAGE_MALDIVES = "mv";
    const CONTENT_LANGUAGE_MALI = "ml";
    const CONTENT_LANGUAGE_MALTA = "mt";
    const CONTENT_LANGUAGE_MARSHALL_ISLANDS = "mh";
    const CONTENT_LANGUAGE_MARTINIQUE = "mq";
    const CONTENT_LANGUAGE_MAURITANIA = "mr";
    const CONTENT_LANGUAGE_MAURITIUS = "mu";
    const CONTENT_LANGUAGE_MAYOTTE = "yt";
    const CONTENT_LANGUAGE_MEXICO = "mx";
    const CONTENT_LANGUAGE_MICRONESIA_FEDERATED_STATES_OF = "fm";
    const CONTENT_LANGUAGE_MOLDOVA_REPUBLIC_OF = "md";
    const CONTENT_LANGUAGE_MONACO = "mc";
    const CONTENT_LANGUAGE_MONGOLIA = "mn";
    const CONTENT_LANGUAGE_MONTENEGRO = "me";
    const CONTENT_LANGUAGE_MONTSERRAT = "ms";
    const CONTENT_LANGUAGE_MOROCCO = "ma";
    const CONTENT_LANGUAGE_MOZAMBIQUE = "mz";
    const CONTENT_LANGUAGE_MYANMAR = "mm";
    const CONTENT_LANGUAGE_NAMIBIA = "na";
    const CONTENT_LANGUAGE_NAURU = "nr";
    const CONTENT_LANGUAGE_NEPAL = "np";
    const CONTENT_LANGUAGE_NETHERLANDS = "nl";
    const CONTENT_LANGUAGE_NEW_CALEDONIA = "nc";
    const CONTENT_LANGUAGE_NEW_ZEALAND = "nz";
    const CONTENT_LANGUAGE_NICARAGUA = "ni";
    const CONTENT_LANGUAGE_NIGER = "ne";
    const CONTENT_LANGUAGE_NIGERIA = "ng";
    const CONTENT_LANGUAGE_NIUE = "nu";
    const CONTENT_LANGUAGE_NORFOLK_ISLAND = "nf";
    const CONTENT_LANGUAGE_NORTHERN_MARIANA_ISLANDS = "mp";
    const CONTENT_LANGUAGE_NORWAY = "no";
    const CONTENT_LANGUAGE_OMAN = "om";
    const CONTENT_LANGUAGE_PAKISTAN = "pk";
    const CONTENT_LANGUAGE_PALAU = "pw";
    const CONTENT_LANGUAGE_PALESTINIAN_TERRITORY_OCCUPIED = "ps";
    const CONTENT_LANGUAGE_PANAMA = "pa";
    const CONTENT_LANGUAGE_PAPUA_NEW_GUINEA = "pg";
    const CONTENT_LANGUAGE_PARAGUAY = "py";
    const CONTENT_LANGUAGE_PERU = "pe";
    const CONTENT_LANGUAGE_PHILIPPINES = "ph";
    const CONTENT_LANGUAGE_PITCAIRN = "pn";
    const CONTENT_LANGUAGE_POLAND = "pl";
    const CONTENT_LANGUAGE_PORTUGAL = "pt";
    const CONTENT_LANGUAGE_PUERTO_RICO = "pr";
    const CONTENT_LANGUAGE_QATAR = "qa";
    const CONTENT_LANGUAGE_RÉUNION = "re";
    const CONTENT_LANGUAGE_ROMANIA = "ro";
    const CONTENT_LANGUAGE_RUSSIAN_FEDERATION = "ru";
    const CONTENT_LANGUAGE_RWANDA = "rw";
    const CONTENT_LANGUAGE_SAINT_BARTHÉLEMY = "bl";
    const CONTENT_LANGUAGE_SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA = "sh";
    const CONTENT_LANGUAGE_SAINT_KITTS_AND_NEVIS = "kn";
    const CONTENT_LANGUAGE_SAINT_LUCIA = "lc";
    const CONTENT_LANGUAGE_SAINT_MARTIN_FRENCH_PART = "mf";
    const CONTENT_LANGUAGE_SAINT_PIERRE_AND_MIQUELON = "pm";
    const CONTENT_LANGUAGE_SAINT_VINCENT_AND_THE_GRENADINES = "vc";
    const CONTENT_LANGUAGE_SAMOA = "ws";
    const CONTENT_LANGUAGE_SAN_MARINO = "sm";
    const CONTENT_LANGUAGE_SAO_TOME_AND_PRINCIPE = "st";
    const CONTENT_LANGUAGE_SAUDI_ARABIA = "sa";
    const CONTENT_LANGUAGE_SENEGAL = "sn";
    const CONTENT_LANGUAGE_SERBIA = "rs";
    const CONTENT_LANGUAGE_SEYCHELLES = "sc";
    const CONTENT_LANGUAGE_SIERRA_LEONE = "sl";
    const CONTENT_LANGUAGE_SINGAPORE = "sg";
    const CONTENT_LANGUAGE_SINT_MAARTEN_DUTCH_PART = "sx";
    const CONTENT_LANGUAGE_SLOVAKIA = "sk";
    const CONTENT_LANGUAGE_SLOVENIA = "si";
    const CONTENT_LANGUAGE_SOLOMON_ISLANDS = "sb";
    const CONTENT_LANGUAGE_SOMALIA = "so";
    const CONTENT_LANGUAGE_SOUTH_AFRICA = "za";
    const CONTENT_LANGUAGE_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = "gs";
    const CONTENT_LANGUAGE_SOUTH_SUDAN = "ss";
    const CONTENT_LANGUAGE_SPAIN = "es";
    const CONTENT_LANGUAGE_SRI_LANKA = "lk";
    const CONTENT_LANGUAGE_SUDAN = "sd";
    const CONTENT_LANGUAGE_SURINAME = "sr";
    const CONTENT_LANGUAGE_SVALBARD_AND_JAN_MAYEN = "sj";
    const CONTENT_LANGUAGE_SWAZILAND = "sz";
    const CONTENT_LANGUAGE_SWEDEN = "se";
    const CONTENT_LANGUAGE_SWITZERLAND = "ch";
    const CONTENT_LANGUAGE_SYRIAN_ARAB_REPUBLIC = "sy";
    const CONTENT_LANGUAGE_TAIWAN_PROVINCE_OF_CHINA = "tw";
    const CONTENT_LANGUAGE_TAJIKISTAN = "tj";
    const CONTENT_LANGUAGE_TANZANIA_UNITED_REPUBLIC_OF = "tz";
    const CONTENT_LANGUAGE_THAILAND = "th";
    const CONTENT_LANGUAGE_TIMOR_LESTE = "tl";
    const CONTENT_LANGUAGE_TOGO = "tg";
    const CONTENT_LANGUAGE_TOKELAU = "tk";
    const CONTENT_LANGUAGE_TONGA = "to";
    const CONTENT_LANGUAGE_TRINIDAD_AND_TOBAGO = "tt";
    const CONTENT_LANGUAGE_TUNISIA = "tn";
    const CONTENT_LANGUAGE_TURKEY = "tr";
    const CONTENT_LANGUAGE_TURKMENISTAN = "tm";
    const CONTENT_LANGUAGE_TURKS_AND_CAICOS_ISLANDS = "tc";
    const CONTENT_LANGUAGE_TUVALU = "tv";
    const CONTENT_LANGUAGE_UGANDA = "ug";
    const CONTENT_LANGUAGE_UKRAINE = "ua";
    const CONTENT_LANGUAGE_UNITED_ARAB_EMIRATES = "ae";
    const CONTENT_LANGUAGE_UNITED_KINGDOM = "gb";
    const CONTENT_LANGUAGE_UNITED_STATES = "us";
    const CONTENT_LANGUAGE_UNITED_STATES_MINOR_OUTLYING_ISLANDS = "um";
    const CONTENT_LANGUAGE_URUGUAY = "uy";
    const CONTENT_LANGUAGE_UZBEKISTAN = "uz";
    const CONTENT_LANGUAGE_VANUATU = "vu";
    const CONTENT_LANGUAGE_VENEZUELA_BOLIVARIAN_REPUBLIC_OF = "ve";
    const CONTENT_LANGUAGE_VIET_NAM = "vn";
    const CONTENT_LANGUAGE_VIRGIN_ISLANDS_BRITISH = "vg";
    const CONTENT_LANGUAGE_VIRGIN_ISLANDS_US = "vi";
    const CONTENT_LANGUAGE_WALLIS_AND_FUTUNA = "wf";
    const CONTENT_LANGUAGE_WESTERN_SAHARA = "eh";
    const CONTENT_LANGUAGE_YEMEN = "ye";
    const CONTENT_LANGUAGE_ZAMBIA = "zm";
    const CONTENT_LANGUAGE_ZIMBABWE = "zw";
    ## Message Status Code
    public static function getStatusMessage($code){
        $statusMessages = array(
            self::_100_CONTINUE => "continue",
            self::_101_SWITCHING_PROTOCOLS => "switching Protocols",
            self::_102_PROCESSING => "processing",
            self::_200_OK => "ok",
            self::_201_CREATED => "created",
            self::_202_ACCEPTED => "accepted",
            self::_203_NON_AUTHORITATIVE_INFORMATION => "non authoritative information",
            self::_204_NO_CONTENT => "no_content",
            self::_205_RESET_CONTENT => "reset content",
            self::_206_PARTIAL_CONTENT => "partial content",
            self::_207_MULTI_STATUS => "multi status",
            self::_210_CONTENT_DIFFERENT => "content different",
            self::_226_IM_USED => "im used",
            self::_300_MULTIPLE_CHOICES => "multiple choices",
            self::_301_MOVED_PERMANENTLY => "moved permanently",
            self::_302_MOVED_TEMPORARILY => "moved temporarily",
            self::_303_SEE_OTHER => "see other",
            self::_304_NOT_MODIFIED => "not modified",
            self::_305_USE_PROXY => "use proxy",
            self::_307_TEMPORARY_REDIRECT => "temporary redirect",
            self::_308_PERMANENT_REDIRECT => "permanent redirect",
            self::_310_TOO_MANY_REDIRECTS => "too many redirects",
            self::_400_BAD_REQUEST => "bad request",
            self::_401_UNAUTHORIZED => "unauthorized",
            self::_402_PAYMENT_REQUIRED => "payment required",
            self::_403_FORBIDDEN => "forbidden",
            self::_404_NOT_FOUND => "not found",
            self::_405_METHOD_NOT_ALLOWED => "method not allowed",
            self::_406_NOT_ACCEPTABLE => "not acceptable",
            self::_407_PROXY_AUTHENTICATION_REQUIRED => "proxy authentication required",
            self::_408_REQUEST_TIME_OUT => "request time out",
            self::_409_CONFLICT => "conflict",
            self::_410_GONE => "gone",
            self::_411_LENGTH_REQUIRED => "length required",
            self::_412_PRECONDITION_FAILED => "precondition failed",
            self::_413_REQUEST_ENTITY_TOO_LARGE => "request entity too large",
            self::_414_REQUEST_URI_Too_Long => "request uri too long",
            self::_415_UNSUPPORTED_MEDIA_TYPE => "unsupported media type",
            self::_416_REQUESTED_RANGE_UNSATISFIABLE => "requested range unsatisfiable",
            self::_417_EXPECTATION_FAILED => "expectation failed",
            self::_418_IM_A_TEAPOT => "im a teapot",
            self::_422_UNPROCESSABLE_ENTITY => "unprocessable entity",
            self::_423_LOCKED => "locked",
            self::_424_METHOD_FAILURE => "method failure",
            self::_425_UNORDERED_COLLECTION => "unordered collection",
            self::_426_UPGRADE_REQUIRED => "upgrade required",
            self::_428_PRECONDITION_REQUIRED => "precondition required",
            self::_429_TOO_MANY_REQUESTS => "too many requests",
            self::_431_REQUEST_HEADER_FIELDS_TOO_LARGE => "request header fields too large",
            self::_449_RETRY_WITH => "retry with",
            self::_450_BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS => "blocked by windows parental controls",
            self::_451_UNAVAILABLE_FOR_LEGAL_REASONS => "unavailable for legal reasons",
            self::_456_UNRECOVERABLE_ERROR => "unrecoverable error",
            self::_499_CLIENT_HAS_CLOSED_CONNECTION => "client has closed connection",
            self::_500_INTERNAL_SERVER_ERROR => "internal server error",
            self::_501_NOT_IMPLEMENTED => "not implemented",
            self::_502_BAD_GATEWAY => "bad gateway",
            self::_503_SERVICE_UNAVAILABLE => "service unavailable",
            self::_504_GATEWAY_TIME_OUT => "gateway time out",
            self::_505_HTTP_VERSION_NOT_SUPPORTED => "http version not supported",
            self::_506_VARIANT_ALSO_NEGOCIATE => "variant also negociate",
            self::_507_INSUFFICIENT_STORAGE => "insufficient storage",
            self::_508_LOOP_DETECTED => "loop detected",
            self::_509_BANDWIDTH_LIMIT_EXCEEDED => "bandwidth limit exceeded",
            self::_510_NOT_EXTENDED => "123not extended",
            self::_511_NETWORK_AUTHENTICATION_REQUIRED => "network authentication required",
            self::_520_WEB_SERVER_IS_RETURNING_AN_UNKNOWN_ERROR => "web server is returning an unknown error"
        );
        return $statusMessages[$code];
    }

   /*
    * REQUEST
    */
    ## ...

    /*
     * SERVER ??
     */
    ## ...
}